### PR TITLE
add sort page, modify page order, add resources

### PR DESCRIPTION
**Pull request by byandell**

### CODE REVIEW

**Comment by byandell** [comment]
I believe I have resolved the conflict for 03-save-export.md for my gh-pages branch, but I did not make changes in add-sort branch for that.

In addition, I added another short lesson for examining numbers. See yandell_changes.md.

**Comment by tracykteal** [comment]
Thanks @byandell, these are great additions to the lesson, and I'm sorry for the slow review on the PR. These look good to go in. There were a couple minor merge conflicts, that I'm resolving.

**Comment by byandell** [comment]
Tracy,
Thanks. I understand some instructors keep clear of the scatterplot in favor of doing that kind of activity in R. It seems to me it doesn't hurt to have that material for completeness.
Cheers,
Brian

**Comment by tracykteal** [comment]
Thanks! Merged. Excited to have this content as a part of the lesson!

**Pull request merged**
